apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
  namespace: akshat   # <-- added namespace
spec:
  type: LoadBalancer
  selector:
    app: bookmyshow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
